### ISSUE TITLE
abe madarchod ke bachee kya code likhaa heee has has ke pagal ho jaungaaa

### ISSUE THREAD

**Issue by shivkemaakechut** [ShivanshMalik2/SubdomainHunter#1]
madarchodd tere see chotee bachee isse achaa code likhtehhh hai , lavdee ke shakall bsdkk bughunter banegaaahh nikal madarcoddd sab automation ho raha hai tu bug hunter banega jab tak bug hunter banegaa tab tak market chukhaa hogaa madarchodd nikal idharr se bsdkk.

**Comment by ShivanshMalik2** [comment]
Bhai ye baat last baar sunle,
Jo bhi tu hai muje teri gaaliyon se ghanta farak padta hai. 
Aur beta me itna free nahi hu jo terese ladunga, Ill just go on. Ja jo karna hai tereko karle
